name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar deploy na VM
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |
            cd /opt/actus_fit_v1/Actus_web

            git pull origin main

            docker compose up -d --build
